- hosts: all
#  connection: local
  module_defaults:
    group/redhat.openshift:
      host: "{{ openshift_api_url }}"
      validate_certs: false
  vars_files:
    - secret.yml
  roles:
    - managednamespace
