- hosts: localhost
#  connection: local
  module_defaults:
    redhat.openshift.k8s:
      host: "{{ openshift_api_url }}"
      validate_certs: false
  vars_files:
    - secret.yml
  roles:
    - managednamespace
